In [2]:
import torch
import torch.nn as nn

net = nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,1))
X = torch.rand(size=(2,4))
net(X)

tensor([[-0.1918],
        [-0.1046]], grad_fn=<AddmmBackward0>)

In [3]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[ 0.2563,  0.0934, -0.1272, -0.2592, -0.0735, -0.0668,  0.0187, -0.1541]])),
             ('bias', tensor([-0.1201]))])

In [8]:
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([-0.1201], requires_grad=True)
tensor([-0.1201])


In [9]:
print(*[(name, param.shape) for name, param in net[0].named_parameters()])
print(*[(name, param.shape) for name, param in net.named_parameters()])

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


ValueError: too many values to unpack (expected 2)